"
""aaa""
"
Class {
	#name : #Cuoora,
	#superclass : #Object,
	#instVars : [
		'cuoora',
		'usuariosCreados',
		'topicos'
	],
	#category : #Cuoora
}

{ #category : #accessing }
Cuoora >> cuoora [
	^ cuoora
]

{ #category : #accessing }
Cuoora >> cuoora: anObject [
	cuoora := anObject
]

{ #category : #accessing }
Cuoora >> topicos [
	^ topicos
]

{ #category : #accessing }
Cuoora >> topicos: anObject [
	topicos := anObject
]

{ #category : #accessing }
Cuoora >> usuariosCreados [
	^ usuariosCreados
]

{ #category : #accessing }
Cuoora >> usuariosCreados: anObject [
	usuariosCreados := anObject
]
